### ISSUE TITLE
要做app了吗

### ISSUE THREAD

**Issue by hklisuper** [110/ITbook-Issues#1]
现在不弄沟通群了吗

**Comment by 110** [comment]
@hklisuper 出事了，所以群全解散了。 再等等吧。 这也没啥好办法。或者进TG群吧

**Comment by xiurierye** [comment]
玲z 请问。。。那个 bdwp  的 群  内容 还。。。在嘛～～～

**Comment by hklisuper** [comment]
玲子，现在已经下载不了，下载链接访问不了

**Comment by 110** [comment]
tg群有新的 微信群 链接。 可以先入微信群。
