### ISSUE TITLE
搜索框输入汉字后界面会卡死

### ISSUE THREAD

**Issue by oppos69** [110/ITbook-Issues#3]
搜索框输入汉字后界面会卡死

**Comment by oppos69** [comment]
输入汉字界面卡死后，关闭窗口可是程序依然在运行，并且占用了大量资源
![微信截图_20210322102427](https://user-images.githubusercontent.com/7611143/111932741-0c225b00-8af9-11eb-9c9d-8f06f2bd7bd1.png)

**Comment by 110** [comment]
@oppos69  好 我看看。

**Comment by 110** [comment]
Try this 

https://github.com/110/ITbook-Issues/releases/tag/1.3

When I Test New Version， CPU Not So  Hight

**Comment by 110** [comment]
@oppos69

**Comment by oppos69** [comment]
that‘s fixed ,Thanks
